# Generated by Django 4.2 on 2025-07-15 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('company_name', models.CharField(max_length=150)),
                ('domain', models.CharField(max_length=100)),
                ('employment_type', models.CharField(choices=[('Full‑time', 'Full‑time'), ('Part‑time', 'Part‑time'), ('Contract', 'Contract'), ('Internship', 'Internship')], default='Full‑time', max_length=20)),
                ('salary_min_lpa', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('salary_max_lpa', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('experience_level', models.CharField(choices=[('Fresher', 'Fresher'), ('0‑2 Yrs', '0‑2 Yrs'), ('2‑5 Yrs', '2‑5 Yrs'), ('5+ Yrs', '5+ Yrs')], default='Fresher', max_length=20)),
                ('location', models.CharField(blank=True, max_length=120, null=True)),
                ('remote_allowed', models.BooleanField(default=False)),
                ('apply_by', models.DateField(blank=True, null=True)),
                ('job_description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('Engineering', 'Engineering'), ('Management', 'Management'), ('Design', 'Design'), ('Marketing', 'Marketing'), ('Finance', 'Finance')], default='Engineering', max_length=20)),
            ],
        ),
    ]
