# Generated by Django 4.2 on 2025-07-15 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='category',
            field=models.CharField(choices=[('Human Resources', 'Human Resources'), ('Software Development', 'Software Development'), ('Marketing', 'Marketing'), ('Operations', 'Operations'), ('Finance', 'Finance')], max_length=50),
        ),
    ]
