# Generated by Django 4.2 on 2025-07-16 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_alter_job_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('host_org', models.CharField(max_length=150)),
                ('category', models.CharField(choices=[('Free', 'Free'), ('Paid', 'Paid')], default='Free', max_length=4)),
                ('fee_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('competition_type', models.CharField(choices=[('Case‑Study', 'Case‑Study'), ('Hackathon', 'Hackathon'), ('Quiz', 'Quiz'), ('Idea‑Thon', 'Idea‑Thon'), ('Other', 'Other')], default='Other', max_length=10)),
                ('mode', models.CharField(choices=[('Online', 'Online'), ('Offline', 'Offline'), ('Hybrid', 'Hybrid')], default='Online', max_length=7)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('prize_pool', models.CharField(blank=True, max_length=120, null=True)),
                ('team_size', models.CharField(default='Individual', max_length=20)),
                ('registration_deadline', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
