# Generated by Django 4.2 on 2025-07-16 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_competition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='competition_type',
            field=models.CharField(choices=[('Competitions', 'Competitions'), ('Hackathons', 'Hackathons'), ('Quizzes', 'Quizzes'), ('Scholarships', 'Scholarships'), ('Workshops', 'Workshops'), ('Conferences', 'Conferences'), ('Cultural Events', 'Cultural Events')], max_length=20),
        ),
    ]
