# Generated by Django 4.2 on 2025-07-17 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_internshipapplication'),
        ('mainapp', '0005_alter_competition_competition_type'),
    ]

    operations = [
    ]
