# Generated by Django 4.2 on 2025-07-17 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_merge_20250717_1337'),
        ('mainapp', '0006_merge_20250717_1355'),
    ]

    operations = [
    ]
