# Generated by Django 4.2 on 2025-07-19 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_merge_20250717_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='employment_type',
            field=models.CharField(choices=[('Full-time', 'Full-time'), ('Part-time', 'Part-time'), ('Contract', 'Contract'), ('Internship', 'Internship')], default='Full‑time', max_length=20),
        ),
        migrations.DeleteModel(
            name='InternshipApplication',
        ),
    ]
