# Generated by Django 4.2 on 2025-07-21 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_candidateprofile_profile_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppliedInternship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('payment_status', models.CharField(choices=[('Success', 'Success'), ('Unsuccess', 'Unsuccess'), ('Not Applicable', 'Not Applicable')], default='Not Applicable', max_length=20)),
                ('candidate', models.ForeignKey(db_column='candidate_id', on_delete=django.db.models.deletion.CASCADE, related_name='applied_internships', to='mainapp.candidateprofile')),
                ('internship', models.ForeignKey(db_column='internship_id', on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='mainapp.internship')),
            ],
            options={
                'db_table': 'mainapp_appliedinternship',
                'unique_together': {('candidate', 'internship')},
            },
        ),
    ]
