# Generated by Django 4.2 on 2025-07-21 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_appliedinternship'),
    ]

    operations = [
        migrations.AddField(
            model_name='appliedinternship',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='appliedinternship',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='appliedinternship',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
