# Generated by Django 4.2 on 2025-07-21 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_appliedinternship_email_appliedinternship_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appliedinternship',
            name='category',
            field=models.CharField(blank=True, choices=[('Paid', 'Paid'), ('Unpaid', 'Unpaid')], max_length=20),
        ),
        migrations.AddField(
            model_name='appliedinternship',
            name='internship_company_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='appliedinternship',
            name='internship_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='appliedinternship',
            name='mode',
            field=models.CharField(blank=True, choices=[('Online', 'Online'), ('Offline', 'Offline')], max_length=20),
        ),
        migrations.AddField(
            model_name='appliedinternship',
            name='stipend_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
