# Generated by Django 4.2 on 2025-07-21 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_appliedinternship_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appliedinternship',
            name='category',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='appliedinternship',
            name='internship_company_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='appliedinternship',
            name='internship_title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='appliedinternship',
            name='mode',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
