# Generated by Django 4.2 on 2025-07-21 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0013_alter_appliedinternship_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppliedForJob',
            fields=[
                ('application_id', models.AutoField(primary_key=True, serialize=False)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=255)),
                ('company_name', models.CharField(max_length=255)),
                ('domain', models.CharField(max_length=100)),
                ('employment_type', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_applications', to='mainapp.candidateprofile')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_applicants', to='mainapp.job')),
            ],
            options={
                'db_table': 'mainapp_appliedforjob',
                'unique_together': {('candidate', 'job')},
            },
        ),
    ]
