# Generated by Django 4.2 on 2025-07-21 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0014_appliedforjob'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetitionsApplied',
            fields=[
                ('application_id', models.AutoField(primary_key=True, serialize=False)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=255)),
                ('host_org', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=100)),
                ('fee_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('competition_type', models.CharField(max_length=100)),
                ('mode', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('team_size', models.IntegerField()),
                ('prize_pool', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competition_applications', to='mainapp.candidateprofile')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applicants', to='mainapp.competition')),
            ],
            options={
                'db_table': 'mainapp_competitions_applied',
                'unique_together': {('candidate', 'competition')},
            },
        ),
    ]
