# Generated by Django 4.2 on 2025-07-21 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0015_competitionsapplied'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitionsapplied',
            name='team_size',
            field=models.CharField(max_length=50),
        ),
    ]
