# Generated by Django 4.2 on 2025-07-24 01:05

from django.db import migrations, models
import mainapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0016_alter_competitionsapplied_team_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('designation', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to=mainapp.models.upload_to_admin_photos)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
