# Generated by Django 4.2 on 2025-07-24 11:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainapp', '0017_adminmodule'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminmodule',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adminmodule', to=settings.AUTH_USER_MODEL),
        ),
    ]
