# Generated by Django 4.2 on 2025-07-24 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0018_adminmodule_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
