# Generated by Django 4.2 on 2025-07-30 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0020_company_password_alter_company_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='courses_accepted',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='college',
            name='domains_accepted',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='email',
            field=models.EmailField(default='default@example.com', max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='company',
            name='password',
            field=models.CharField(default='default@example.com', max_length=128),
            preserve_default=False,
        ),
    ]
