# Generated by Django 4.2 on 2025-07-30 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0021_alter_college_courses_accepted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='courses_accepted',
            field=models.TextField(blank=True, help_text='Comma-separated courses like: B.Tech, M.Tech', null=True),
        ),
        migrations.AlterField(
            model_name='college',
            name='domains_accepted',
            field=models.TextField(blank=True, help_text='Comma-separated subjects like: Computer Science, Mechanical', null=True),
        ),
    ]
